# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: imodel-unity-example-node-$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'windows-latest'
trigger:
  branches:
    include: [ master ]
  paths:
    include: [ node ]

steps:
  - task: NodeTool@0
    displayName: 'Use Node.js 14.x'
    inputs:
      versionSpec: '14.x'
  
  - script: npm install
    displayName: npm install
    workingDirectory: '$(Build.SourcesDirectory)/node'

  - script: npm run build
    displayName: npm run build
    workingDirectory: '$(Build.SourcesDirectory)/node'

  - script: npm run lint
    displayName: npm run lint
    workingDirectory: '$(Build.SourcesDirectory)/node'
